import os
import sys

# setup global wildcards
SAMPLES, = glob_wildcards("{sample}.fna")

# RULES TO INCLUDE
include: "rules/01_ORF_finding.smk"
include: "rules/02_microcin_hmm.smk"
include: "rules/03_merge_hmmsearch.smk"
include: "rules/04_analyze_outputs.smk"
include: "rules/05_signal_hmm.smk"
include: "rules/06_clean_outputs.smk"

# TARGET OUTPUT
rule final:
    input:
        config["outdir"] + "/results/final/final_output.csv",
        config["outdir"] + "/results/remove_temp_files.txt"
