name: MicSearch

channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda

dependencies:
  - seqkit=0.15.0
  - mafft=7.475
  - hmmer=3.3.1
  - blast=2.9.0
  - diamond=2.0.11
  - pandas=1.2.4
  - numpy=1.19.2
  - biopython=1.76
  - snakemake=6.2.1
  - prodigal=2.6.3
  - pyhmmer=0.3.0
  - pip
  - pip:
    - pyTMHMM==1.3.2
    - seqhash==1.0.0
    - blake3==0.2.0
