#!/bin/bash

: '
Use this script to run the pipeline on the CSV file generated by `data_organization.ipynb`.
First, ensure you have downloaded the necessary .fna and .fastq.gz files from the IBDMDB database.
'

# Check if the correct number of arguments are provided (1)
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <csv_file>"
  exit 1
fi

# Assign the first argument to the variable CSV_FILE
CSV_FILE=$1

# Read the CSV file and extract the first and second columns
while IFS=',' read -r sample_id sequence; do
  # Create the paths for genome_fna, read1, and read2 using sample_id
  genome_fna="dna_data/${sample_id}_contigs.fna"
  read1="rna_data/${sample_id}_R1.fastq.gz"
  read2="rna_data/${sample_id}_R2.fastq.gz"

  # Check if the necessary files exist
  if [[ -f "$genome_fna" && -f "$read1" && -f "$read2" ]]; then
    echo "Files for sample ID $sample_id found, proceeding with pipeline."
    
    # Remove newline characters from the sequence
    sequence=$(echo "$sequence" | tr -d '\n')
    
    # Run the Python script pipeline.py with the generated paths and sequence
    python3 pipeline.py --genome_fna "$genome_fna" --read1 "$read1" --read2 "$read2" --target_sequence "$sequence"
  else
    echo "Missing files for sample ID $sample_id. Skipping..."
  fi
done < "$CSV_FILE"
