from snakemake.utils import min_version
import os
import sys

# set minimum snakemake version
#min_version("6.2.1")


# setup report

#configfile: "config/config.yaml"

#report: "report/workflow.rst"

# setup conda


# load rules

include: "rules/setup_inputs.smk"
include: "rules/prodigal.smk"
include: "rules/nonredundant_prodigal.smk"
include: "rules/filter_microcin.smk"
include: "rules/ss_hmmer.smk"
include: "rules/hmm_scan.smk"


# target rules

rule final:
    input:
        "results/database/SP.verified.aln",
        "results/prodigal/prodigal_out.all.nr.faa",
        "results/prodigal/prodigal_out.all.nr_expanded.csv",
        "results/microcins/filtered_nr.fa",
        "results/signalSeq/SS.verified.hmm",
        "results/phmmer/ss_hmm_tblout.txt",
        "results/hmmsearch/hmmsearch_tblout.txt"
